export const DUMMY_RECIPE_DATA = [
  {
    recipeID: "R001",
    recipeName: "Idli",
    recipeType: "Vegetarian",
    category: "Breakfast",
    cuisine: "South Indian",
    createdDateTime: "01/01/2025",
  },
  {
    recipeID: "R002",
    recipeName: "Dosa",
    recipeType: "Vegetarian",
    category: "Breakfast",
    cuisine: "South Indian",
    createdDateTime: "02/01/2025",
  },
  {
    recipeID: "R003",
    recipeName: "Vegetable Upma",
    recipeType: "Vegetarian",
    category: "Breakfast",
    cuisine: "South Indian",
    createdDateTime: "03/01/2025",
  },
  {
    recipeID: "R004",
    recipeName: "Sambar",
    recipeType: "Vegetarian",
    category: "Lunch",
    cuisine: "South Indian",
    createdDateTime: "04/01/2025",
  },
  {
    recipeID: "R005",
    recipeName: "Rasam",
    recipeType: "Vegetarian",
    category: "Lunch",
    cuisine: "South Indian",
    createdDateTime: "05/01/2025",
  },
  {
    recipeID: "R006",
    recipeName: "Vegetable Kurma",
    recipeType: "Vegetarian",
    category: "Lunch",
    cuisine: "South Indian",
    createdDateTime: "06/01/2025",
  },
  {
    recipeID: "R007",
    recipeName: "Lemon Rice",
    recipeType: "Vegetarian",
    category: "Lunch",
    cuisine: "South Indian",
    createdDateTime: "07/01/2025",
  },
  {
    recipeID: "R008",
    recipeName: "Curd Rice",
    recipeType: "Vegetarian",
    category: "Dinner",
    cuisine: "South Indian",
    createdDateTime: "08/01/2025",
  },
  {
    recipeID: "R009",
    recipeName: "Vegetable Pongal",
    recipeType: "Vegetarian",
    category: "Breakfast",
    cuisine: "South Indian",
    createdDateTime: "09/01/2025",
  },
  {
    recipeID: "R010",
    recipeName: "Tomato Thokku",
    recipeType: "Vegetarian",
    category: "Side Dish",
    cuisine: "South Indian",
    createdDateTime: "10/01/2025",
  },
];
