export const DUMMY_RECIPE_DATA = [
  {
    recipeID: "R001",
    recipeName: "Idli",
    recipeType: "Veg",
    cuisine: "South Indian",
    category: "Breakfast",
    ingredients: ["Rice", "Urad Dal", "Salt", "Water"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    difficulty: "Easy",
    serves: 4,
    youtubeVideoUrl: "https://www.youtube.com/watch?v=VzgzG2guCZo",
  },
  {
    recipeID: "R002",
    recipeName: "Masala Dosa",
    recipeType: "Veg",
    cuisine: "South Indian",
    category: "Breakfast",
    ingredients: ["Rice", "Urad Dal", "Potato", "Onion", "Green Chilli"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    difficulty: "Medium",
    serves: 3,
    youtubeVideoUrl: "https://www.youtube.com/c/MadrasSamayal/videos",
  },
  {
    recipeID: "R003",
    recipeName: "Vegetable Sambar",
    recipeType: "Veg",
    cuisine: "South Indian",
    category: "Lunch",
    ingredients: ["Toor Dal", "Drumstick", "Carrot", "Tomato", "Tamarind"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: "Easy",
    serves: 4,
    youtubeVideoUrl: "https://www.youtube.com/c/MadrasSamayal/videos",
  },
  {
    recipeID: "R004",
    recipeName: "Curd Rice",
    recipeType: "Veg",
    cuisine: "South Indian",
    category: "Lunch",
    ingredients: ["Rice", "Curd", "Mustard Seeds", "Green Chilli"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "Easy",
    serves: 3,
    youtubeVideoUrl: "https://www.youtube.com/c/MadrasSamayal/videos",
  },
  {
    recipeID: "R005",
    recipeName: "Rava Upma",
    recipeType: "Veg",
    cuisine: "South Indian",
    category: "Breakfast",
    ingredients: [
      "Rava",
      "Onion",
      "Green Chilli",
      "Mustard Seeds",
      "Curry Leaves",
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "Easy",
    serves: 2,
    youtubeVideoUrl: "https://www.youtube.com/watch?v=X0Fl_FhKKzU",
  },
  {
    recipeID: "R006",
    recipeName: "Vegetable Kootu",
    recipeType: "Veg",
    cuisine: "South Indian",
    category: "Lunch",
    ingredients: ["Chow Chow", "Toor Dal", "Coconut", "Cumin"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    difficulty: "Medium",
    serves: 4,
    youtubeVideoUrl: "https://www.youtube.com/c/MadrasSamayal/videos",
  },
  {
    recipeID: "R007",
    recipeName: "Avial",
    recipeType: "Veg",
    cuisine: "South Indian",
    category: "Lunch",
    ingredients: [
      "Carrot",
      "Beans",
      "Drumstick",
      "Raw Banana",
      "Coconut",
      "Curd",
    ],
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    difficulty: "Medium",
    serves: 4,
    youtubeVideoUrl: "https://www.youtube.com/c/MadrasSamayal/videos",
  },
  {
    recipeID: "R008",
    recipeName: "Chicken Chettinad",
    recipeType: "Non-Veg",
    cuisine: "South Indian",
    category: "Dinner",
    ingredients: ["Chicken", "Onion", "Tomato", "Coconut", "Chettinad Masala"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: "Medium",
    serves: 4,
    youtubeVideoUrl: "https://www.youtube.com/watch?v=4YyMKK0gdZk",
  },
  {
    recipeID: "R009",
    recipeName: "Lemon Rice",
    recipeType: "Veg",
    cuisine: "South Indian",
    category: "Lunch",
    ingredients: ["Rice", "Lemon", "Peanuts", "Mustard Seeds", "Turmeric"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "Easy",
    serves: 3,
    youtubeVideoUrl: "https://www.youtube.com/c/MadrasSamayal/videos",
  },
  {
    recipeID: "R010",
    recipeName: "Medu Vada",
    recipeType: "Veg",
    cuisine: "South Indian",
    category: "Snack",
    ingredients: ["Urad Dal", "Onion", "Green Chilli", "Curry Leaves", "Oil"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    difficulty: "Medium",
    serves: 4,
    youtubeVideoUrl: "https://www.youtube.com/c/MadrasSamayal/videos",
  },
];
